development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: shopstack_development
      # Provides the hosts the default client can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - <%= ENV['MLAB_HOST'] %>
      options:
        user: <%= ENV['DB_USER'] %>
        password: <%= ENV['DB_USER_PASSWORD'] %>

production:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: shopstack_production
      # Provides the hosts the default client can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - <%= ENV['MLAB_HOST'] %>
      options:
        user: <%= ENV['DB_USER'] %>
        password: <%= ENV['DB_USER_PASSWORD'] %>

  options:

test:
  clients:
    default:
      database: shopstack_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
