# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5849f5123b1a7f3701f7f2ff16b09d95986ddc2f753ad99b79c32dac71a624932c149c13b187f28b8e4012fdc9e6248652cd0144ad712055fddc20869abbe248

test:
  secret_key_base: f11258437fe23f378e32a6a311579238eca5190ca47c8d5eb0bb284f3afa2ad2e65a28b509f781d7665cf4f8e56bb32551fc411b886d19536e188424ce101706

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
